-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "email" VARCHAR(255),
ADD COLUMN     "image" VARCHAR(500),
ADD COLUMN     "lastLoginAt" TIMESTAMP(3),
ADD COLUMN     "name" VARCHAR(255);
