FROM oven/bun:1.2

# 作業ディレクトリを設定
WORKDIR /app/backend

# package.json と bun.lock をコピー（キャッシュ活用）
COPY backend/package.json backend/bun.lock ./

# 依存インストール
RUN bun install

# ソースコード全体をコピー
COPY backend ./

# Prisma Client を生成
RUN bun drizzle-kit generate
# エントリポイント
CMD ["bun", "run", "dev"]
