FROM node:20-alpine

WORKDIR /app

COPY frontend ./frontend
COPY packages ./packages

WORKDIR /app/packages/shared-types
RUN npm install

WORKDIR /app/frontend
RUN npm install
RUN npm run prebuild

CMD ["npm", "run", "dev"]
