FROM node:22-alpine
ENV CI=true

WORKDIR /app

COPY frontend ./frontend
COPY packages ./packages

RUN npm install -g pnpm

WORKDIR /app/packages/shared-types
RUN npm install

WORKDIR /app/frontend


RUN pnpm install
RUN pnpm run prebuild

CMD ["pnpm", "run", "dev"]
